{{ if not .Values.usedAsSubchart }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kraken-configmap
data:
  krakend.json: |-
{{- if eq .Values.krakendJson "" }}
{{ .Files.Get "krakend.json" | indent 4 }}
{{- else }}
{{ .Values.krakendJson | indent 4 }}
{{- end}}
{{- end}}