apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "krakend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "krakend.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ template "krakend.fullname" . }}-configmap
        {{- if .Values.flexible_config.enabled }}
        - name: settings-config
          configMap:
            name: settings-configmap
            optional: true
        - name: partials-config
          configMap:
            name: partials-configmap
            optional: true
        - name: templates-config
          configMap:
            name: templates-configmap
            optional: true
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "krakend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.flexible_config.enabled }}
          env:
            - name: FC_ENABLE
              value: "1"
            - name: FC_SETTINGS
              value: "/etc/krakend/flexible_config/settings"
            - name: FC_PARTIALS
              value: "/etc/krakend/flexible_config/partials"
            - name: FC_TEMPLATES
              value: "/etc/krakend/flexible_config/templates"
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/krakend/
            {{- if .Values.flexible_config.enabled }}
            - name: settings-config
              mountPath: /etc/krakend/flexible_config/settings
            - name: partials-config
              mountPath: /etc/krakend/flexible_config/partials
            - name: templates-config
              mountPath: /etc/krakend/flexible_config/templates
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness.probe | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness.probe | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            {{- toYaml .Values.probes.startup.probe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
