{{- if .Values.flexible_config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-configmap
data:
{{ (.Files.Glob "flexible-configuration/settings/*").AsConfig | indent 4 }}
{{- end }}