{{- if and (.Values.flexible_config.enabled) ( eq (.Files.Glob "flexible-configuration/templates/*").AsConfig "" ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: templates-configmap
data:
{{ (.Files.Glob "flexible-configuration/templates/*").AsConfig | indent 4 }}
{{- end }}